### ISSUE TITLE
Manifest version deprecated

### ISSUE THREAD

**Issue by Krisvanth** [Zerg00s/Live-Captions-Saver#2]
Hi,

I'm trying to run the extension in developer mode but I'm still getting the below error. 

"Manifest version 2 is deprecated, and support will be removed in 2023. See https://developer.chrome.com/blog/mv2-transition/ for more details."

Can you convert the manifest.json into manifest version 3? 

Thanks,
Kris

**Comment by Zerg00s** [comment]
hi @Krisvanth,

It's a great idea! But unfortunately, it might take me a few weeks to get to it 😟

I'll try my best to make it work though.

**Comment by Krisvanth** [comment]
Hi,
That's sounds good,

**Comment by Krisvanth** [comment]
Hi,
That sounds good ! Feel free to reach out once it is done.

Thanks,
Kris

**Comment by Krisvanth** [comment]
Hi @Zerg00s,
Just checking in to see if you've had a chance to work on it or if there's any update on the project.

Thanks,
Kris

**Comment by Zerg00s** [comment]
hi @Krisvanth,

I've tried upgrading to manifest v3. But it's much more restrictive, and I still need to figure out how to make the extension work reliably.

**Comment by Zerg00s** [comment]
@Krisvanth , I drafter a new version that is not very reliable, but it's the best I have so far: [https://github.com/Zerg00s/Live-Captions-Saver/releases/tag/v3](https://github.com/Zerg00s/Live-Captions-Saver/releases/tag/v3)

**Comment by Krisvanth** [comment]
Hi @Zerg00s ,
Thanks for upgrading this to manifest v3 but still when I tried to download the crx file it threw the following error and stopped downloading "Package is invalid:'CRX_REQUIRED_PROOF_MISSING'". I attached the screenshot below. 

Thanks,
Kris
![image](https://github.com/Zerg00s/Live-Captions-Saver/assets/88583624/c72f6ff2-c989-41c6-aeb3-35076f6b4648)

**Comment by Zerg00s** [comment]
Hi Chris, looks like it's a standard Chrome issue for custom extensions.

Can you, please, install this extension manually? https://www.thesslstore.com/blog/install-a-chrome-extension/
