### ISSUE TITLE
Where Does The Caption File Save?

### ISSUE THREAD

**Issue by blackhawk23x** [Zerg00s/Live-Captions-Saver#6]
Curious where the file saves or how do I access the data. Also how do I know it's working?

**Comment by Zerg00s** [comment]
hi @blackhawk23x . The captions are saved in the browser's memory, locally. The file is generated only when you try to download the cations. To check if the captions are captured - try downloading them. If thr downloaded file contains data - it works.

**Comment by blackhawk23x** [comment]
What I currently see is this and clicking save captions does nothing. Tried both browser extension and the unpack option. I believe I'm in the new teams my link has /v2/ at the end. Any tips on how to make this work?
![image](https://github.com/Zerg00s/Live-Captions-Saver/assets/51942359/19008477-dfb7-4efc-9dae-4ce3501e43b2)
